### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by Johswald** [ganguli-lab/pathint#4]
Hey - one quick question. I scanned the code a bit but could not find any data augmentation on cifar 10 / cifar 100. Is that correct? The results reported in the paper on the cifar 10/100 task are achieved by training on the cifar 10 / cifar 100 without data augmentation?  
Many thanks!

**Comment by fzenke** [comment]
Yes, that's correct. We did not use any data augmentation.

**Comment by Johswald** [comment]
Thank you for the quick reply!
